### ISSUE TITLE
Issue python3 stats.py

### ISSUE THREAD

**Issue by MineraleYT** [MinerAle00/rpi5oled#1]
Dopo aver seguito la guida dando questo comando `python3 stats.py` compare questo messaggio di errore

`Traceback (most recent call last):
  File "/home/minerale/OLED_Stats/stats.py", line 16, in <module>
    oled_reset = digitalio.DigitalInOut(board.D4)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/minerale/oled_env/lib/python3.11/site-packages/digitalio.py", line 193, in __init__
    self.direction = Direction.INPUT
    ^^^^^^^^^^^^^^
  File "/home/minerale/oled_env/lib/python3.11/site-packages/digitalio.py", line 223, in direction
    self._pin.init(mode=Pin.IN)
  File "/home/minerale/oled_env/lib/python3.11/site-packages/adafruit_blinka/microcontroller/bcm283x/pin.py", line 40, in init
    GPIO.setup(self.id, GPIO.IN)
RuntimeError: Cannot determine SOC peripheral base address`

**Comment by MineraleYT** [comment]
Fix temporaneo grazie a questo utente sul [Forum di raspberry](https://forums.raspberrypi.com/viewtopic.php?t=361218).
```
sudo apt remove python3-rpi.gpio
pip3 install rpi-lgpio
```

**Comment by MineraleYT** [comment]
Il codice originale faceva uso della libreria **digitalio** di CircuitPython per gestire i pin GPIO, in particolare il pin di reset del display OLED. Tuttavia, poiché **digitalio** non è completamente compatibile con il Raspberry Pi 5 o con l’ultima versione del sistema operativo, ho dovuto sostituirla con la libreria **gpiod**.

La libreria **gpiod** fornisce un’interfaccia a basso livello per controllare i pin GPIO sui sistemi Linux, rendendola più adatta per questo progetto. Ho quindi configurato il chip GPIO e impostato il pin di reset come uscita, utilizzandolo per resettare il display.

Ho mantenuto la funzionalità per ottenere le statistiche di sistema (indirizzo IP, carico della CPU, utilizzo della memoria, spazio su disco e temperatura) tramite comandi Linux eseguiti con subprocess, visualizzandole poi sul display OLED.

Commit: https://github.com/MinerAle00/rpi5oled/commit/020d03ea9ba5c075ad023ed9875da388b88ada2f
